---
name: "ci"

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

permissions:
  attestations: write
  id-token: write
  contents: write

jobs:
  ci:
    name: ci
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Pak Name
        id: pak-name
        run: |
          echo "PAK_NAME=$(jq -r .label config.json)" >> $GITHUB_OUTPUT

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Run make build
        run: make clean build

      - name: Create Release zip
        run: |
          mkdir -p dist
          git archive --format=zip --output "dist/${{ steps.pak-name.outputs.PAK_NAME }}.pak.zip" HEAD
          while IFS= read -r line; do
            IFS=' ' read -r -a array <<< "$line"
            zip -ur "dist/${{ steps.pak-name.outputs.PAK_NAME }}.pak.zip" "${array[0]}"
          done < .gitarchiveinclude
          ls -lah dist

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v2.1.0
        with:
          subject-path: "dist/${{ steps.pak-name.outputs.PAK_NAME }}.pak.zip"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*
